[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
pusd_spl = "9ftLECMyJfEk27kjxyrs3cPh8h6EtKET7gpj8v2RqN1e"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"
# wallet = "~/.config/solana/wallets/account3.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
